### ISSUE TITLE
"Edit on GitHub link" is broken

### ISSUE THREAD

**Issue by dunglas** [api-platform/website#75]
The change introduced by #72 is broken.

https://api-platform.com/docs/core/serialization/#the-serialization-process

The generated URL is `https://github.com/api-platform/docs/edit/undefined/core/serialization.md`...
Can you fix this @Mathieudewet please?

By the way the test of the link should be "Edit this page on GitHub".

**Comment by Mathieudewet** [comment]
Testing it while getting the upstream master state on my laptop is working.
I wonder if it's not du to OS version because of sed when trying to get the current branch.
Not sure how to verify this without more information about prod server.
Can we check that, we could verify that the `docsBranchName` key in constants.js is fullify well ?

**Comment by dunglas** [comment]
Try to enable the Travis build on your branch...

**Comment by Mathieudewet** [comment]
In my travis build :

```
$ cat constants.js
module.exports = Object.freeze({
  docPagesDirectory: `${__dirname}/src/pages/docs`,
  docsBranchName: 2.3,
});
```

**Comment by Mathieudewet** [comment]
But there is no `docsBranchName` in prod source constants.js file.

![screenshot from 2018-08-24 11-36-28](https://user-images.githubusercontent.com/10513229/44577695-0d007e00-a792-11e8-9c5b-f8980aeac7c9.png)

**Comment by Mathieudewet** [comment]
What is weird too is on Upstream travis build, it seems to be resolved as well  too : https://travis-ci.org/api-platform/website/builds/419632820#
